CREATE TABLE IF NOT EXISTS trips (
  ID INT NOT NULL,
  START_COORDS VARCHAR NOT NULL,
  PLANNED_END_COORDS VARCHAR NOT NULL,
  ACTUAL_END_COORDS VARCHAR,
  CUSTOMER_ID UUID NOT NULL,
  RATE NUMERIC NOT NULL,
  STATUS VARCHAR NOT NULL, 
  PROJECTED_PRICE NUMERIC,
  FINAL_PRICE NUMERIC,
  DISTANCE_TRAVELLED NUMERIC,
  FLAG VARCHAR NOT NULL
)